### ISSUE TITLE
Create the "product binding" page

### ISSUE THREAD

**Issue by sakuya9t** [clara-lan/Emergency-Button#5]
## Story
We want to bind the product (life button) with user accounts. There should be a page doing this. Similar to the register and login pages, this page should contain a form that users can record the information needed. Such as the product ID.

This function should only be available after the user login. If the user have not logged in, they are led to the login page.

## Tasks
- [ ] There should be a page doing this
- [ ] If the user hasn't logged in, they are redirected to the login page.
- [ ] When a user clicks the "product binding" navigation bar they are led to this page.
- [ ] There is a form recoding this info and there should be a submission button.
