### ISSUE TITLE
Display user name after logging in.

### ISSUE THREAD

**Issue by sakuya9t** [clara-lan/Emergency-Button#6]
## Story
After a user clicks the "login" button on the login page, their user name should appear somewhere on the page (the right top corner for example). 

The user name displayed should be the same as their input (say the email address).

After user login, they can hover the mouse on their username, and a dropdown containing the "log out" label should appear. Once clicking on the "logout", the page should return to the state before logging in.

## Tasks
- [ ] After the user clicks the "login" button, their username should be displayed.
- [ ] Before clicking the login button, the username should not appear on the page.
- [ ] After logging in, the "login" and "register" labels should disappear from the navigation bar.
- [ ] The dropdown menu should appear when the user hovers the mouse on their username, which contains a "logout" label.
- [ ] After clicking the "logout", their username should disappear from the page, and the "login" is visible again.
